plugins {
    id 'com.github.jruk8.plugin-conventions' version 'v1.1.5'
    id 'com.gradleup.shadow' version '9.3.1'
}

dependencies {
    implementation 'org.bstats:bstats-bukkit:3.2.1'
}

tasks.shadowJar {
    configurations = [project.configurations.runtimeClasspath]

    dependencies {
        // Only merge bStats into the final jar, no other dependencies
        exclude { it.moduleGroup != "org.bstats" }
    }

    relocate("org.bstats", project.group.toString())
}
