pluginGroup=com.jruk8
pluginName=JBlockGlitch
pluginMain=com.jruk8.jblockglitch.JBlockGlitchPlugin
pluginAuthor=jruk8
pluginDescription=Prevents block placement glitches in protected regions
pluginWebsite=https://github.com/jruk8/JBlockGlitch
paperApiVersion=26.2.build.+
systemProp.org.eclipse.jgit.transport.ssh=ssh
systemProp.GIT_SSH=ssh