name: ${name}
version: ${version}
main: ${main}
api-version: "${apiVersion}"
author: ${author}
description: ${description}
website: ${website}

commands:
  jblockglitch:
    description: JBlockGlitch main command
    usage: /jblockglitch <help|reload>
    aliases:
      - jbg
    permission: jblockglitch.help
  help:
    description: Show JBlockGlitch documentation
    usage: /jblockglitch:help
    permission: jblockglitch.help
  reload:
    description: Reload JBlockGlitch configuration and messages
    usage: /jblockglitch:reload
    permission: jblockglitch.reload

permissions:
  jblockglitch.help:
    description: View JBlockGlitch documentation
    default: true
  jblockglitch.reload:
    description: Reload JBlockGlitch configuration and messages
    default: op
